package org.CBank.Test;

import org.jb2011.lnf.beautyeye.BeautyEyeLookAndFeelCross;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/* 
 * testUI.java 
 * 
 * Created on __DATE__, __TIME__ 
 */  
  
/** 
 * 
 * @author  __USER__ 
 */  
public class testUI extends JFrame {
  
    /** Creates new form testUI */  
    public testUI() {  
        initComponents();  
    }  
  
    /** This method is called from within the constructor to 
     * initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is 
     * always regenerated by the Form Editor. 
     */  
    //GEN-BEGIN:initComponents  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">  
    private void initComponents() {  
  
        jLabel1 = new javax.swing.JLabel();  
        jLabel2 = new javax.swing.JLabel();  
        jTextField1 = new javax.swing.JTextField();  
        jPasswordField1 = new javax.swing.JPasswordField();  
        jButton1 = new javax.swing.JButton();  
  
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);  
  
        jLabel1.setText("\u8d26\u53f7\uff1a");  
  
        jLabel2.setText("\u5bc6\u7801\uff1a");  
  
        jButton1.setText("\u767b\u5f55");  
        jButton1.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				 try {
					UIManager  
					 .setLookAndFeel(new BeautyEyeLookAndFeelCross());
				} catch (UnsupportedLookAndFeelException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}  
			}
		});
  
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(  
                getContentPane());  
        getContentPane().setLayout(layout);  
        layout.setHorizontalGroup(layout  
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
                .addGroup(  
                        layout.createSequentialGroup()  
                                .addGap(63, 63, 63)  
                                .addGroup(  
                                        layout.createParallelGroup(  
                                                javax.swing.GroupLayout.Alignment.LEADING)  
                                                .addComponent(jLabel1)  
                                                .addComponent(jLabel2))  
                                .addPreferredGap(  
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)  
                                .addGroup(  
                                        layout.createParallelGroup(  
                                                javax.swing.GroupLayout.Alignment.LEADING)  
                                                .addComponent(  
                                                        jButton1,  
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,  
                                                        90,  
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)  
                                                .addGroup(  
                                                        layout.createParallelGroup(  
                                                                javax.swing.GroupLayout.Alignment.TRAILING)  
                                                                .addComponent(  
                                                                        jTextField1,  
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,  
                                                                        129,  
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)  
                                                                .addComponent(  
                                                                        jPasswordField1,  
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,  
                                                                        129,  
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))  
                                .addContainerGap(77, Short.MAX_VALUE)));  
        layout.setVerticalGroup(layout  
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
                .addGroup(  
                        layout.createSequentialGroup()  
                                .addGap(67, 67, 67)  
                                .addGroup(  
                                        layout.createParallelGroup(  
                                                javax.swing.GroupLayout.Alignment.BASELINE)  
                                                .addComponent(jLabel1)  
                                                .addComponent(  
                                                        jTextField1,  
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,  
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,  
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))  
                                .addGap(39, 39, 39)  
                                .addGroup(  
                                        layout.createParallelGroup(  
                                                javax.swing.GroupLayout.Alignment.BASELINE)  
                                                .addComponent(jLabel2)  
                                                .addComponent(  
                                                        jPasswordField1,  
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,  
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,  
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))  
                                .addGap(32, 32, 32).addComponent(jButton1)  
                                .addContainerGap(28, Short.MAX_VALUE)));  
  
        pack();  
    }// </editor-fold>  
    //GEN-END:initComponents  
  
    /** 
     * @param args the command line arguments 
     */  
    public static void main(String args[]) {  
        java.awt.EventQueue.invokeLater(new Runnable() {  
            public void run() {  
                ////////////////////����Ƥ������/////////////////  
                JFrame.setDefaultLookAndFeelDecorated(true);  
                JDialog.setDefaultLookAndFeelDecorated(true);  
                try  
                {  
                    UIManager.setLookAndFeel(UIManager  
                            .getCrossPlatformLookAndFeelClassName());  
//                    UIManager  
//                            .setLookAndFeel(new BeautyEyeLookAndFeelCross());  
//                    // UIManager.setLookAndFeel(new SubstanceBusinessLookAndFeel());  
                }  
                catch (Exception e)  
                {  
                    e.printStackTrace();  
                }  
                ///////////////////////////////////////////////  
                testUI frame = new testUI();
                frame.setVisible(true);  
                frame.setUndecorated(true);
            }  
        });  
    }  
  
    //GEN-BEGIN:variables  
    // Variables declaration - do not modify  
    private javax.swing.JButton jButton1;  
    private javax.swing.JLabel jLabel1;  
    private javax.swing.JLabel jLabel2;  
    private javax.swing.JPasswordField jPasswordField1;  
    private javax.swing.JTextField jTextField1;  
    // End of variables declaration//GEN-END:variables  
  
}  